### ISSUE TITLE
The content cannot be set on a BinaryFileResponse instance.

### ISSUE THREAD

**Issue by tuxes3** [spinbits/sylius-google-analytics-plugin#33]
I have some custom Actions in the backend of my sylius application. Your listener `Spinbits\SyliusGoogleAnalytics4Plugin\EventListener\RenderViewListener` tries to set the content on a BinaryFileResponse, which is prohibited and results in a 500 error. 

I fixed it with a decorator of your `RenderViewListener` service:

```php
    public function onKernelResponse(ResponseEvent $event): void
    {
        if ($event->getResponse() instanceof BinaryFileResponse) {
            return;
        }

        $this->renderViewListener->onKernelResponse($event);
    }
```

**Comment by LouisBertin** [comment]
Hi @tuxes3 I encountered the same problem for a `StreamedResponse` .

Do you think your decorator works for both cases ?

**Comment by LouisBertin** [comment]
And how do you register your decorator ? Here is my configuration : 

```yaml
Spinbits\SyliusGoogleAnalytics4Plugin\EventListener\RenderViewListener: ~
App\Service\Spinbits\SyliusGoogleAnalytics4Plugin\EventListener\RenderViewListener:
    decorates: Spinbits\SyliusGoogleAnalytics4Plugin\EventListener\RenderViewListener
    arguments:
      [ '@.inner' ]
``` 

When I run `symfony console debug:event-dispatcher kernel.response` I got the following error : 
```bash
In RenderViewListener.php line 18:
                                                                                                                                                                                                                               
Too few arguments to function Spinbits\SyliusGoogleAnalytics4Plugin\EventListener\RenderViewListener::__construct(), 0 passed in
```

**Comment by LouisBertin** [comment]
Finally, I don't know why, but it works with this configuration : 

```yaml
Spinbits\SyliusGoogleAnalytics4Plugin\EventListener\RenderViewListener:
    class: Spinbits\SyliusGoogleAnalytics4Plugin\EventListener\RenderViewListener
    arguments:
      [ '@Spinbits\SyliusGoogleAnalytics4Plugin\Factory\RenderHeadTwigFactory' ]
App\Service\Spinbits\SyliusGoogleAnalytics4Plugin\EventListener\RenderViewListener:
    decorates: Spinbits\SyliusGoogleAnalytics4Plugin\EventListener\RenderViewListener
    arguments: ['@.inner']
```
